INSERT INTO bears (name, age, breed)
  VALUES ("Mr.Chocolate", 60, "Black Bear")
INSERT INTO bears (name, age, breed)
  VALUES ("Rowdy", 24, "Space Bear")
INSERT INTO bears (name, age, breed)
  VALUES ("Tabitha", 14, "Care Bear")
INSERT INTO bears (name, age, breed)
  VALUES ("Sergeant Brown", 16, "Army Bear")
INSERT INTO bears (name, age, breed)
  VALUES ("Melissa", 42, "Momma Bear")
INSERT INTO bears (name, age, breed)
  VALUES ("Grinch", 60, "Mean ")
INSERT INTO bears (name, age, breed)
  VALUES ("Wendy", 100, "Bear")
INSERT INTO bears (name, age, breed)
  VALUES ("NULL", 40, "Killed Tim")
